2024-09-11 21:17:02,699 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 21:17:02,700 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 21:38:16,177 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 21:38:16,177 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 21:38:46,817 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 21:38:46,817 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 21:42:40,234 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 21:42:40,234 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 21:44:40,435 INFO: Microblog startup [in /home/tingchieh/Documents/flask-study/app/__init__.py:62]
2024-09-11 21:44:40,435 INFO: 19dc547d60e6421ab862b8ea304ac0ff [in /home/tingchieh/Documents/flask-study/app/__init__.py:63]
2024-09-11 21:44:42,277 ERROR: Exception on /categories [GET] [in /home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/app/routes.py", line 490, in categories
    return render_template('categories.html', form=form, categories=categories)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/tingchieh/Documents/flask-study/app/templates/categories.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/tingchieh/Documents/flask-study/app/templates/base.html", line 97, in top-level template code
    {% block content %}
  File "/home/tingchieh/Documents/flask-study/app/templates/categories.html", line 29, in block 'content'
    <a href="{{ url_for('edit_category', category_id=category.id) }}" class="btn btn-sm btn-secondary">Edit</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'edit_category' with values ['category_id']. Did you mean 'delete_category' instead?
2024-09-11 21:44:43,940 ERROR: Exception on /categories [GET] [in /home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/app/routes.py", line 490, in categories
    return render_template('categories.html', form=form, categories=categories)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/tingchieh/Documents/flask-study/app/templates/categories.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/tingchieh/Documents/flask-study/app/templates/base.html", line 97, in top-level template code
    {% block content %}
  File "/home/tingchieh/Documents/flask-study/app/templates/categories.html", line 29, in block 'content'
    <a href="{{ url_for('edit_category', category_id=category.id) }}" class="btn btn-sm btn-secondary">Edit</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tingchieh/Documents/flask-study/.venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'edit_category' with values ['category_id']. Did you mean 'delete_category' instead?
